name: Build and Push Docker Images
on:
  push:
    branches: [main]
    paths: [Versions/4.0/**]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Images
        run: |
          set -ex

          version=4.0
          docker build --rm --tag "swiftfiddle/swift:$version" "Versions/$version" && docker push "swiftfiddle/swift:$version"
